# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='principal',
            field=models.CharField(max_length=256),
        ),
    ]
