# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecords',
            new_name='AccessRecord',
        ),
        migrations.RenameField(
            model_name='accessrecord',
            old_name='url',
            new_name='name',
        ),
    ]
